const LANGUAGES = {
  EN: {
    RANGE_M: 'Range M (4 - 25)',
    RANGE_N: 'Range N (10 - 25)',
    ITERATIONS: 'Iterations (5 - 10)',
    RESET_BUTTON: 'RESET',
    SHIFT_BUTTON: 'SHIFT',
    ITERATION_COUNTER: '<mark>*</mark> - iteration counter',
    TASK: 'Task:',
    POINT_1: `<mark>The</mark> initial positioning of the tokens is such that the first two columns have green tokens and the remaining columns have red tokens;`,
    POINT_2: `<mark>For</mark> each token, a number between 1 and 4 is chosen;;`,
    POINT_3: `<mark>One</mark> by one, each token is swapped places with a token located in the same row, in the column with the number that was selected in point b.`,
    POINT_4: `<mark>After</mark> all the tokens have been swapped, operations b-c are repeated four more times.`,
    MODIFIED: `<mark>Modified</mark>: the board can be of size MxN (limited to 25 each, because why many?) and the number of iterations can be from 5 to 10 (limited for the same reason).`,
  },
  RU: {
    RANGE_M: 'Диапазон M (4 - 25)',
    RANGE_N: 'Диапазон N (10 - 25)',
    ITERATIONS: 'Итераций (5 - 10)',
    RESET_BUTTON: 'СБРОС',
    SHIFT_BUTTON: 'СТАРТ',
    ITERATION_COUNTER: '<mark>*</mark> - счетчик итераций',
    TASK: 'Задача:',
    POINT_1: `<mark>Начальное</mark> расположение фишек таково, что первые два столбца имеют зеленые фишки, а остальные столбцы имеют красные фишки;`,
    POINT_2: `<mark>Для</mark> каждой фишки выбирается число от 1 до 4;`,
    POINT_3: `<mark>По</mark> одной каждая фишка меняется местами с фишкой, расположенной в том же ряду, в столбце с номером, который был выбран в пункте b.`,
    POINT_4: `<mark>После</mark> того, как все фишки будут поменяны местами, операции b-c повторяются еще четыре раза.`,
    MODIFIED: `<mark>Изменено</mark>: доска может быть размером MxN (ограничены до  25 каждый, потому что зачем много?) и количество итераций может быть от 5 до 10 (ограничено по той же причине).`,
  },
  PL: {
    RANGE_M: 'Zakres M (4 - 25)',
    RANGE_N: 'Zakres N (10 - 25)',
    ITERATIONS: 'Iteracje (5 - 10)',
    RESET_BUTTON: 'RESET',
    SHIFT_BUTTON: 'ZMIANA',
    ITERATION_COUNTER: '<mark>*</mark> - licznik iteracji',
    TASK: 'Zadanie:',
    POINT_1: `<mark>Początkowe</mark> ustawienie żetonów jest takie, że pierwsze dwie kolumny mają zielone żetony, a pozostałe kolumny mają czerwone żetony;`,
    POINT_2: `<mark>Dla</mark> każdego żetonu rysuje się liczba od 1 do 4;`,
    POINT_3: `<mark>Jeden</mark> po drugim każdy żeton jest zamieniany miejscami z żetonem znajdującym się w tym samym rzędzie, w kolumnie z numerem, który został narysowany w punkcie b.`,
    POINT_4: `<mark>Po</mark> tym, jak wszystkie żetony zostaną zamienione miejscami, operacje b-c są powtarzane jeszcze cztery razy.`,
    MODIFIED: `<mark>Zmodyfikowano</mark>: plansza może mieć rozmiar MxN (ograniczone do 25 każdy) i liczba iteracji może wynosić od 5 do 10.`,
  },
};
